[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/a-new-climate"
  to = "/a-new-climate/events/san-francisco"
[[redirects]]
  from = "/a-new-climate/events"
  to = "/a-new-climate/events/san-francisco"
[[redirects]]
  from = "/a-new-climate/events/san-francisco/program"
  to = "/a-new-climate/events/san-francisco"
[[redirects]]
  from = "/a-new-climate/events/san-francisco/speakers"
  to = "/a-new-climate/events/san-francisco"
[[redirects]]
  from = "/a-new-climate/events/san-francisco/ticketing"
  to = "/a-new-climate/events/san-francisco/dialog/ticketing"
[[redirects]]
  from = "/a-new-climate/events/san-francisco/tickets"
  to = "/a-new-climate/events/san-francisco/dialog/ticketing"
[[redirects]]
  from = "/a-new-climate/events/san-francisco/venue"
  to = "/a-new-climate/events/san-francisco"
[[redirects]]
  from = "/a-new-climate/san-francisco"
  to = "/a-new-climate/events/san-francisco"
[[redirects]]
  from = "/a-new-climate/san-francisco-preview-page"
  to = "/a-new-climate/events/san-francisco"
[[redirects]]
  from = "/a-new-climate/sanfrancisco"
  to = "/a-new-climate/events/san-francisco"

[[redirects]]
  from = "/climate-forward/events"
  to = "/climate-forward/"
[[redirects]]
  from = "/climate-forward/events/london/program"
  to = "/climate-forward/events/london"
[[redirects]]
  from = "/climate-forward/events/london/speakers"
  to = "/climate-forward/events/london"
[[redirects]]
  from = "/climate-forward/events/london/ticketing"
  to = "/climate-forward/events/london/dialog/ticketing"
[[redirects]]
  from = "/climate-forward/events/london/tickets"
  to = "/climate-forward/events/london/dialog/ticketing"
[[redirects]]
  from = "/climate-forward/events/london/venue"
  to = "/climate-forward/events/london"
[[redirects]]
  from = "/climate-forward/events/new-york/program"
  to = "/climate-forward/events/new-york"
[[redirects]]
  from = "/climate-forward/events/new-york/speakers"
  to = "/climate-forward/events/new-york"
[[redirects]]
  from = "/climate-forward/events/new-york/ticketing"
  to = "/climate-forward/events/new-york/dialog/ticketing"
[[redirects]]
  from = "/climate-forward/events/new-york/tickets"
  to = "/climate-forward/events/new-york/dialog/ticketing"
[[redirects]]
  from = "/climate-forward/events/new-york/venue"
  to = "/climate-forward/events/new-york"
[[redirects]]
  from = "/climate-forward/fashion-opportunity"
  to = "/climate-forward/the-fashion-opportunity"
[[redirects]]
  from = "/climate-forward/london"
  to = "/climate-forward/events/london"
[[redirects]]
  from = "/climate-forward/new-york"
  to = "/climate-forward/events/new-york"
[[redirects]]
  from = "/climate-forward/new-york-preview-page"
  to = "/climate-forward/events/new-york"
[[redirects]]
  from = "/climate-forward/newyork"
  to = "/climate-forward/events/new-york"
[[redirects]]
  from = "/fashion-opportunity"
  to = "/climate-forward/the-fashion-opportunity"
[[redirects]]
  from = "/the-fashion-opportunity"
  to = "/climate-forward/the-fashion-opportunity"
[[redirects]]
  from = "/the-fashion-opportunity/speakers"
  to = "/climate-forward/the-fashion-opportunity"
[[redirects]]
  from = "/the-fashion-opportunity/speakers/*"
  to = "/climate-forward/the-fashion-opportunity"

[[redirects]]
  from = "/a-new-climate/*"
  to = "/a-new-climate-404"
  status = 404
[[redirects]]
  from = "/climate-forward/*"
  to = "/climate-forward-404"
  status = 404
[[redirects]]
  from = "/*"
  to = "/404"
  status = 404
